### PR TITLE
nepalimdbAPI

### PR DESCRIPTION
**Pull request by saroz014**
I've added API functionality to this project. Few lines of code has also been added to nepalimdb.py to make it work with the API.

### CODE REVIEW

**Comment by NISH1001** [comment]
Hi, Thanks!
I will check the PR and get back to this thread. Seems like CLI and API has been mixed from a quick inspection. Will it be possible to seggregate the API from CLI itself so that both will be independent of each other.

Again! I will check it and get back here accordingly! Thanks

**Comment by NISH1001** [comment]
Also one suggestion. Why is the use of Django? It is heavy itself. Maybe flask is needed to create API for this project - bare minimum.
Django has only added extra complexity to the project itself!

**Comment by saroz014** [comment]
> Hi, Thanks!
> I will check the PR and get back to this thread. Seems like CLI and API has been mixed from a quick inspection. Will it be possible to seggregate the API from CLI itself so that both will be independent of each other.
> 
> Again! I will check it and get back here accordingly! Thanks

It might be possible. I'll look into it.

**Comment by saroz014** [comment]
> Also one suggestion. Why is the use of Django? It is heavy itself. Maybe flask is needed to create API for this project - bare minimum.
> Django has only added extra complexity to the project itself!

I haven't looked into flask yet. I work with django and thought it would work out fine for this one.

**Comment by NISH1001** [comment]
Hey. I am gonna close this PR because django seems to be heavy IMHO (and thus clutters the bare necessity) :)

**Comment by saroz014** [comment]
> Hey. I am gonna close this PR because django seems to be heavy IMHO (and thus clutters the bare necessity) :)

ok. no worries.

**Pull request closed without merging**
